---
title: "Yokyo FunOlympics"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(leaflet)
library(DT)
library(rgeolocate)
```


```{r data}
df <- read.delim("C:/Users/Admin/Desktop/cet333/CET333 Laone Tsheole/logfile1.txt")

colnames(df)<-c("IP", "Time","URL", "Status")

```

Column {.sidebar data-width=250}
-----------------------------------------------------------------------
```{r inputs}

fileInput(inputId= NULL, label = "Choose your dataset", multiple = FALSE, accept= NULL, buttonLabel = "Browse weblog file...", placeholder = "No file selected")


```

```{r reactive expression}
##linear regression model
model1 <- reactive({
  vars <- as.matrix(data[, input$variable_choice])
  lm(Status ~ vars, data = data)
})
```

Column {data-width=400}
-----------------------------------------------------------------------

### 

```{r model output}
renderPrint({
  summary(model1())
})

```

```{r table}
DT::renderDataTable({
  DT::datatable(weblogr%>% mutate(predicted = predict(model1()),residuals = residuals(model1()))) %>%select(Status,predicted,residuals)
  rownames = FALSE
  colnames <- c('actual status', 'predicted status', 'residuals') 
  extensions = c('Buttons', 'Responsive')
  options = list(columnDefs = list(list(className = 'dt-center', targets = "_all"))) 
  dom = 'Blfrt'
  buttons = c('copy', 'csv', 'excel', 'print') 
  searching = FALSE 
  lengthMenu = c(20, 100, 1000, nrow(weblogr))
  scrollY = 300
  scrollCollapse = TRUE 
})

```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r scatter}
renderPlotly({

plotly(data = data, y = ~predict(model1()), x = ~Status,
               type = "scatter", mode = "markers",
               marker = list(size = 5,
                             color = '#FFFFFF',
                             line = list(color = '#EA6345', 
                                         width = 2)))
})
```

### Chart C

```{r histogram}

```

```{css}

```

